server:
  port: 8080

spring:
  datasource:
    username: root
    password: 
    url: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false  #模板引擎缓存关闭
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath*:static/mybatis/*Mapper.xml
  type-aliases-package: com.lxn.community.community.bean
  configuration:
    map-underscore-to-camel-case: true



logging:
  file: logs/community.log
  level:
    root: info

github:
  client_id: 
  redirect_uri: http://101.200.82.160/callback


