server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false  #模板引擎缓存关闭
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath*:static/mybatis/*Mapper.xml
  type-aliases-package: com.lxn.demo2.bean
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  accessKeySecret: PqY1CXcUbcxFc3io0FWg8hsmO88qID
  accessKeyId: LTAI4FfU4GHiSg2UaMZkwGYR
  endpoint: oss-cn-beijing.aliyuncs.com
  bucketName: commenity


#pagehelper分页插件配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
logging:
  file: logs/community.log
  level:
    root: info

