server:
  port: 8080

spring:
  datasource:
    username: root
    password: q58565254q
    url: jdbc:mysql://cdb-1yoat894.cd.tencentcdb.com:10105/community?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false  #模板引擎缓存关闭
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath*:static/mybatis/*Mapper.xml
  type-aliases-package: com.lxn.community.community.bean
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  accessKeySecret: PqY1CXcUbcxFc3io0FWg8hsmO88qID
  accessKeyId: LTAI4FfU4GHiSg2UaMZkwGYR
  endpoint: oss-cn-beijing.aliyuncs.com
  bucketName: commenity

logging:
  file: logs/community.log
  level:
    root: info

github:
  client_id: b8bf759495c1fc7dd36f
  redirect_uri: http://101.200.82.160/callback


